version: 0.2
env:
  secrets-manager:
      IMAGE_REPO_NAME: "dev/docker-hub:IMAGE_REPO_NAME"
      IMAGE_TAG: "dev/docker-hub:IMAGE_TAG"
      REPO_USER: "dev/docker-hub:REPO_USER"
      REPO_PWD: "dev/docker-hub:REPO_PWD"
phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $REPO_PWD | docker login --username $REPO_USER --password-stdin
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG