version: '3.8'
services:
  # PostgreSQL
  postgres:
    container_name: postgres
    build: ./postgres
    env_file:
      - ./postgres/.env.postgres
    ports:
      - "5432:5432"
  # Backend
  my-face-recognition-api:
    env_file:
      - .env
    container_name: backend
    build: ./
    volumes:
      - ./:/usr/app/my-face-recognition-api  # map a local current directory: to debug interactively
    command: npm run start:dev # change to npm run start to exclude nodeman
    working_dir: /usr/app/my-face-recognition-api
    ports:
      - "3001:3001"
    links:
      - postgres