apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-fra
  name: my-fra
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-fra
  strategy: {}
  template:
    metadata:
      labels:
        app: my-fra
        role: my-enable-sg-for-pods # enable SG group - see README
    spec:
      containers:
      - image: famaten/my-face-recognition-dev
        name: my-face-recognition-container
        envFrom:
        - secretRef:
            name: my-face-recognition-env
        # resources:
        #   requests:
        #     memory: "256Mi"
        #     cpu: "500m"
        #   limits:
        #     memory: "512Mi"
        #     cpu: "750m"        
status: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-fra
  name: my-fra-svc
spec:
  ports:
  - port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: my-fra
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-fra-svc-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: my-fra-svc
              port:
                number: 3001
